version: '2'
services:
  eureka-server:
    image: zanhsieh/eureka-server
    ports:
     - "8761:8761"
  echo-service:
    image: zanhsieh/echo-service
    depends_on:
     - eureka-server
  zuul-server:
    image: zanhsieh/zuul-server
    depends_on:
     - eureka-server
    ports:
     - "9090:9090"
