apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: echo-service
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: echo-service
spec:
  ports:
  - name: "9098"
    port: 9098
    targetPort: 9098
  selector:
    app: {{ template "fullname" . }}
    service: echo-service
  type: NodePort
