apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: eureka-server
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: eureka-server
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    app: {{ template "fullname" . }}
    service: eureka-server
  type: LoadBalancer
