apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: zuul-server
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: zuul-server
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    app: {{ template "fullname" . }}
    service: zuul-server
  type: LoadBalancer
